(1-5) 確認用パスワードの追加。
monaka0309/ex-emp-management-bugfix pull request #4
Opened 2024-11-22 07:50 UTC by monaka0309

# (1-5) 確認用パスワードの追加をしました。
ご確認お願いいたします。

2024-11-22 08:03 UTC, mokichi42 requested changes
修正お願いします！

2024-11-22 08:03 UTC, mokichi42 commented on src/main/java/com/example/domain/Administrator.java
> +		this.passwordConfirm = passwordConfirm;
これはFormにだけあればいいと思います

2024-11-22 08:03 UTC, mokichi42 commented on src/main/java/com/example/controller/AdministratorController.java
> +			Administrator administrator = new Administrator();
このあたり、BeanUtils.copyPropertiesと処理がかぶるので追記しなくていいと思います

2024-11-22 08:03 UTC, mokichi42 commented
コンフリクトの修正もお願いします！

2024-11-22 08:28 UTC, monaka0309 commented
指摘箇所を修正しました。
ご確認お願いいたします。

2024-11-25 00:27 UTC, mokichi42 approved these changes
OK！！！

2024-11-25 00:27 UTC, merged